require('utils/input')
require('utils/macro')
require('macro/hayato-lessons')

-- Lesson 2.5
local input = Input()
macroHayatoLessons = MacroHayatoLessons(Macro(input))

return input:all()

--joypadSet10 = {
--    [22537] = {
--        ["P1 Cross"] = true,
--    },
--    [22539] = {
--        ["P1 Down"] = true,
--    },
--    [22541] = {
--        ["P1 Cross"] = true,
--    },
--    [22543] = {
--        ["P1 Right"] = true,
--    },
--    [22545] = {
--        ["P1 Right"] = true,
--    },
--    [22547] = {
--        ["P1 Right"] = true,
--    },
--    [22549] = {
--        ["P1 Right"] = true,
--    },
--    [22551] = {
--        ["P1 Cross"] = true,
--    },
--    [23306] = {
--        ["P1 Cross"] = true,
--    },
--    [23308] = {
--        ["P1 Cross"] = true,
--    },
--    [23460] = {
--        ["P1 Right"] = true,
--    },
--    [23462] = {
--        ["P1 Right"] = true,
--    },
--    [23534] = {
--        ["P1 Down"] = true,
--    },
--    [23535] = {
--        ["P1 Up"] = true,
--    },
--    [23616] = {
--        ["P1 Down"] = true,
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [23688] = {
--        ["P1 Left"] = true,
--    },
--    [23690] = {
--        ["P1 Left"] = true,
--    },
--    [23715.19] = {
--        ["P1 Right"] = true,
--    },
--    [23761] = {
--        ["P1 Down"] = true,
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [23879] = {
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [23900.19] = {
--        ["P1 Left"] = true,
--    },
--    [23951] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [24140] = {
--        ["P1 Down"] = true,
--    },
--    [24141] = {
--        ["P1 Up"] = true,
--    },
--    [24220] = {
--        ["P1 Right"] = true,
--    },
--    [24222] = {
--        ["P1 Right"] = true,
--    },
--    [24235] = {
--        ["P1 Left"] = true,
--    },
--    [24237] = {
--        ["P1 Left"] = true,
--    },
--    [24265.15] = {
--        ["P1 Left"] = true,
--    },
--    [24294] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [24785] = {
--        ["P1 Cross"] = true,
--    },
--    [24787] = {
--        ["P1 Cross"] = true,
--    },
--    [24792] = {
--        ["P1 Down"] = true,
--    },
--    [24794] = {
--        ["P1 Cross"] = true,
--    },
--}