require('utils/input')
require('utils/shortcut')

-- Lesson 3.4
local input = Input()
shortcut = Shortcut(input)

return input:all()

--joypadSet14 = {
--    [32660] = {
--        ["P1 Cross"] = true,
--    },
--    [32662] = {
--        ["P1 Down"] = true,
--    },
--    [32664] = {
--        ["P1 Down"] = true,
--    },
--    [32666] = {
--        ["P1 Cross"] = true,
--    },
--    [32668] = {
--        ["P1 Right"] = true,
--    },
--    [32670] = {
--        ["P1 Right"] = true,
--    },
--    [32672] = {
--        ["P1 Right"] = true,
--    },
--    [32674] = {
--        ["P1 Cross"] = true,
--    },
--    [33443] = {
--        ["P1 Cross"] = true,
--    },
--    [33445] = {
--        ["P1 Cross"] = true,
--    },
--    [33597] = {
--        ["P1 Square"] = true,
--    },
--    [33599] = {
--        ["P1 Square"] = true,
--    },
--    [33673] = {
--        ["P1 Square"] = true,
--    },
--    [33675] = {
--        ["P1 Square"] = true,
--    },
--    [33749] = {
--        ["P1 Square"] = true,
--    },
--    [33751] = {
--        ["P1 Square"] = true,
--    },
--    [33765] = {
--        ["P1 Triangle"] = true,
--    },
--    [33836] = {
--        ["P1 Square"] = true,
--    },
--    [33838] = {
--        ["P1 Square"] = true,
--    },
--    [33854] = {
--        ["P1 Triangle"] = true,
--    },
--    [33927] = {
--        ["P1 Square"] = true,
--    },
--    [33929] = {
--        ["P1 Square"] = true,
--    },
--    [34005] = {
--        ["P1 Square"] = true,
--    },
--    [34007] = {
--        ["P1 Square"] = true,
--    },
--    [34023] = {
--        ["P1 Triangle"] = true,
--    },
--    [34096] = {
--        ["P1 Square"] = true,
--    },
--    [34098] = {
--        ["P1 Square"] = true,
--    },
--    [34114] = {
--        ["P1 Triangle"] = true,
--    },
--    [34127] = {
--        ["P1 Left"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [34226] = {
--        ["P1 Square"] = true,
--    },
--    [34228] = {
--        ["P1 Square"] = true,
--    },
--    [34244] = {
--        ["P1 Triangle"] = true,
--    },
--    [34317] = {
--        ["P1 Square"] = true,
--    },
--    [34319] = {
--        ["P1 Square"] = true,
--    },
--    [34395] = {
--        ["P1 Square"] = true,
--    },
--    [34397] = {
--        ["P1 Square"] = true,
--    },
--    [34413] = {
--        ["P1 Triangle"] = true,
--    },
--    [34426] = {
--        ["P1 Left"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [34833] = {
--        ["P1 Cross"] = true,
--    },
--    [34835] = {
--        ["P1 Cross"] = true,
--    },
--    [34840] = {
--        ["P1 Down"] = true,
--    },
--    [34842] = {
--        ["P1 Cross"] = true,
--    },
--}