local Input = require('utils/input')
require('utils/macro')
require('macro/hayato-lessons')

-- Lesson 5.5
local input = Input()

macroHayatoLessons = MacroHayatoLessons(Macro(input))

return input:all()

--joypadSet25 = {
--    [60525] = {
--        ["P1 Cross"] = true,
--    },
--    [60527] = {
--        ["P1 Down"] = true,
--    },
--    [60529] = {
--        ["P1 Down"] = true,
--    },
--    [60531] = {
--        ["P1 Down"] = true,
--    },
--    [60533] = {
--        ["P1 Down"] = true,
--    },
--    [60535] = {
--        ["P1 Cross"] = true,
--    },
--    [60537] = {
--        ["P1 Right"] = true,
--    },
--    [60539] = {
--        ["P1 Right"] = true,
--    },
--    [60541] = {
--        ["P1 Right"] = true,
--    },
--    [60543] = {
--        ["P1 Right"] = true,
--    },
--    [60545] = {
--        ["P1 Cross"] = true,
--    },
--    [61313] = {
--        ["P1 Cross"] = true,
--    },
--    [61315] = {
--        ["P1 Cross"] = true,
--    },
--    [61467.7] = {
--        ["P1 Right"] = true,
--    },
--    [61474] = {
--        ["P1 L1"] = true,
--    },
--    [61686] = {
--        ["P1 Right"] = true,
--    },
--    [61688.32] = {
--        ["P1 Right"] = true,
--    },
--    [61761] = {
--        ["P1 Square"] = true,
--    },
--    [61847] = {
--        ["P1 Down"] = true,
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [61947] = {
--        ["P1 L1"] = true,
--    },
--    [62153] = {
--        ["P1 Left"] = true,
--    },
--    [62155.23] = {
--        ["P1 Left"] = true,
--    },
--    [62228] = {
--        ["P1 Square"] = true,
--    },
--    [62314] = {
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [62411] = {
--        ["P1 Square"] = true,
--    },
--    [62496] = {
--        ["P1 Square"] = true,
--    },
--    [62621] = {
--        ["P1 R2"] = true,
--    },
--    [62703] = {
--        ["P1 L1"] = true,
--    },
--    [62909] = {
--        ["P1 Left"] = true,
--    },
--    [62911.35] = {
--        ["P1 Left"] = true,
--    },
--    [62984] = {
--        ["P1 Square"] = true,
--    },
--    [63360] = {
--        ["P1 Cross"] = true,
--    },
--    [63362] = {
--        ["P1 Cross"] = true,
--    },
--    [63367] = {
--        ["P1 Down"] = true,
--    },
--    [63369] = {
--        ["P1 Cross"] = true,
--    },
--}