local Input = require('utils/input')
require('utils/macro')
require('macro/hayato-lessons')

-- Lesson 6.2
local input = Input()

macroHayatoLessons = MacroHayatoLessons(Macro(input))

return input:all()

--joypadSet27 = {
--    [65665] = {
--        ["P1 Cross"] = true,
--    },
--    [65667] = {
--        ["P1 Down"] = true,
--    },
--    [65669] = {
--        ["P1 Down"] = true,
--    },
--    [65671] = {
--        ["P1 Down"] = true,
--    },
--    [65673] = {
--        ["P1 Down"] = true,
--    },
--    [65675] = {
--        ["P1 Down"] = true,
--    },
--    [65677] = {
--        ["P1 Cross"] = true,
--    },
--    [65679] = {
--        ["P1 Right"] = true,
--    },
--    [65681] = {
--        ["P1 Cross"] = true,
--    },
--    [66437] = {
--        ["P1 Cross"] = true,
--    },
--    [66439] = {
--        ["P1 Cross"] = true,
--    },
--    [66591] = {
--        ["P1 Left"] = true,
--    },
--    [66593] = {
--        ["P1 Left"] = true,
--    },
--    [66654] = {
--        ["P1 Right"] = true,
--    },
--    [66656.18] = {
--        ["P1 Right"] = true,
--    },
--    [66674] = {
--        ["P1 R2"] = true,
--    },
--    [66858] = {
--        ["P1 Square"] = true,
--    },
--    [66860] = {
--        ["P1 Square"] = true,
--    },
--    [66874] = {
--        ["P1 Triangle"] = true,
--    },
--    [66885] = {
--        ["P1 Right"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [66984] = {
--        ["P1 Down"] = true,
--        ["P1 Circle"] = true,
--        ["P1 Cross"] = true,
--    },
--    [67056] = {
--        ["P1 Square"] = true,
--        ["P1 Cross"] = true,
--    },
--    [67363] = {
--        ["P1 Up"] = true,
--    },
--    [67425.35] = {
--        ["P1 Left"] = true,
--    },
--    [67477] = {
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [67540] = {
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [67612] = {
--        ["P1 Left"] = true,
--    },
--    [67614] = {
--        ["P1 Left"] = true,
--    },
--    [67689] = {
--        ["P1 Down"] = true,
--    },
--    [67690] = {
--        ["P1 Up"] = true,
--    },
--    [67771] = {
--        ["P1 Square"] = true,
--    },
--    [67773] = {
--        ["P1 Square"] = true,
--    },
--    [68154] = {
--        ["P1 Cross"] = true,
--    },
--    [68156] = {
--        ["P1 Cross"] = true,
--    },
--    [68161] = {
--        ["P1 Down"] = true,
--    },
--    [68163] = {
--        ["P1 Cross"] = true,
--    },
--}