require('utils/input')
require('utils/shortcut')

-- Lesson 6.3
local input = Input()
shortcut = Shortcut(input)

return input:all()

--joypadSet28 = {
--    [68339] = {
--        ["P1 Cross"] = true,
--    },
--    [68341] = {
--        ["P1 Down"] = true,
--    },
--    [68343] = {
--        ["P1 Down"] = true,
--    },
--    [68345] = {
--        ["P1 Down"] = true,
--    },
--    [68347] = {
--        ["P1 Down"] = true,
--    },
--    [68349] = {
--        ["P1 Down"] = true,
--    },
--    [68351] = {
--        ["P1 Cross"] = true,
--    },
--    [68353] = {
--        ["P1 Right"] = true,
--    },
--    [68355] = {
--        ["P1 Right"] = true,
--    },
--    [68357] = {
--        ["P1 Cross"] = true,
--    },
--    [69119] = {
--        ["P1 Cross"] = true,
--    },
--    [69121] = {
--        ["P1 Cross"] = true,
--    },
--    [69273.27] = {
--        ["P1 Right"] = true,
--    },
--    [69365] = {
--        ["P1 Left"] = true,
--    },
--    [69366] = {
--        ["P1 Square"] = true,
--    },
--    [69462] = {
--        ["P1 Right"] = true,
--    },
--    [69464] = {
--        ["P1 Square"] = true,
--    },
--    [69466] = {
--        ["P1 Square"] = true,
--    },
--    [69526.28] = {
--        ["P1 Right"] = true,
--    },
--    [69565] = {
--        ["P1 R2"] = true,
--    },
--    [69636] = {
--        ["P1 Triangle"] = true,
--    },
--    [69712] = {
--        ["P1 Down"] = true,
--        ["P1 Right"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [69713] = {
--        ["P1 Up"] = true,
--    },
--    [69768] = {
--        ["P1 Square"] = true,
--    },
--    [69880] = {
--        ["P1 L1"] = true,
--    },
--    [70067] = {
--        ["P1 Right"] = true,
--    },
--    [70069.25] = {
--        ["P1 Right"] = true,
--    },
--    [70098] = {
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [70196] = {
--        ["P1 L1"] = true,
--    },
--    [70402] = {
--        ["P1 Right"] = true,
--    },
--    [70404.25] = {
--        ["P1 Right"] = true,
--    },
--    [70470] = {
--        ["P1 Triangle"] = true,
--    },
--    [70549.9] = {
--        ["P1 Right"] = true,
--    },
--    [70558] = {
--        ["P1 Down"] = true,
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [70653] = {
--        ["P1 Triangle"] = true,
--    },
--    [71036] = {
--        ["P1 Cross"] = true,
--    },
--    [71038] = {
--        ["P1 Cross"] = true,
--    },
--    [71043] = {
--        ["P1 Down"] = true,
--    },
--    [71045] = {
--        ["P1 Cross"] = true,
--    },
--}