require('utils/input')
require('utils/shortcut')

-- Lesson 6.4
local input = Input()
shortcut = Shortcut(input)

return input:all()

--joypadSet29 = {
--    [71221] = {
--        ["P1 Cross"] = true,
--    },
--    [71223] = {
--        ["P1 Down"] = true,
--    },
--    [71225] = {
--        ["P1 Down"] = true,
--    },
--    [71227] = {
--        ["P1 Down"] = true,
--    },
--    [71229] = {
--        ["P1 Down"] = true,
--    },
--    [71231] = {
--        ["P1 Down"] = true,
--    },
--    [71233] = {
--        ["P1 Cross"] = true,
--    },
--    [71235] = {
--        ["P1 Right"] = true,
--    },
--    [71237] = {
--        ["P1 Right"] = true,
--    },
--    [71239] = {
--        ["P1 Right"] = true,
--    },
--    [71241] = {
--        ["P1 Cross"] = true,
--    },
--    [71997] = {
--        ["P1 Cross"] = true,
--    },
--    [71999] = {
--        ["P1 Cross"] = true,
--    },
--    [72151] = {
--        ["P1 Square"] = true,
--    },
--    [72153] = {
--        ["P1 Square"] = true,
--    },
--    [72167] = {
--        ["P1 Square"] = true,
--    },
--    [72239] = {
--        ["P1 Square"] = true,
--        ["P1 Cross"] = true,
--    },
--    [72546] = {
--        ["P1 Up"] = true,
--    },
--    [72608.35] = {
--        ["P1 Left"] = true,
--    },
--    [72708] = {
--        ["P1 Left"] = true,
--    },
--    [72709] = {
--        ["P1 Square"] = true,
--    },
--    [72811] = {
--        ["P1 Square"] = true,
--    },
--    [72813] = {
--        ["P1 Square"] = true,
--    },
--    [72884] = {
--        ["P1 L1"] = true,
--    },
--    [73071] = {
--        ["P1 Left"] = true,
--    },
--    [73073.31] = {
--        ["P1 Left"] = true,
--    },
--    [73104] = {
--        ["P1 Cross"] = true,
--        ["P1 Circle"] = true,
--    },
--    [73207] = {
--        ["P1 R2"] = true,
--    },
--    [73282] = {
--        ["P1 Right"] = true,
--    },
--    [73343] = {
--        ["P1 Cross"] = true,
--        ["P1 Square"] = true,
--    },
--    [73650] = {
--        ["P1 Up"] = true,
--    },
--    [73718.6] = {
--        ["P1 Down"] = true,
--    },
--    [74091] = {
--        ["P1 Cross"] = true,
--    },
--    [74093] = {
--        ["P1 Cross"] = true,
--    },
--    [74098] = {
--        ["P1 Down"] = true,
--    },
--    [74100] = {
--        ["P1 Cross"] = true,
--    },
--}