require('utils/input')
require('utils/macro')
require('macro/hayato-lessons')

-- Lesson 6.5
local input = Input()
macroHayatoLessons = MacroHayatoLessons(Macro(input))

return input:all()

--joypadSet30 = {
--    [74276] = {
--        ["P1 Cross"] = true,
--    },
--    [74278] = {
--        ["P1 Down"] = true,
--    },
--    [74280] = {
--        ["P1 Down"] = true,
--    },
--    [74282] = {
--        ["P1 Down"] = true,
--    },
--    [74284] = {
--        ["P1 Down"] = true,
--    },
--    [74286] = {
--        ["P1 Down"] = true,
--    },
--    [74288] = {
--        ["P1 Cross"] = true,
--    },
--    [74290] = {
--        ["P1 Right"] = true,
--    },
--    [74292] = {
--        ["P1 Right"] = true,
--    },
--    [74294] = {
--        ["P1 Right"] = true,
--    },
--    [74296] = {
--        ["P1 Right"] = true,
--    },
--    [74298] = {
--        ["P1 Cross"] = true,
--    },
--    [75069] = {
--        ["P1 Cross"] = true,
--    },
--    [75071] = {
--        ["P1 Cross"] = true,
--    },
--    [75223] = {
--        ["P1 Down"] = true,
--    },
--    [75224] = {
--        ["P1 Down"] = true,
--        ["P1 Left"] = true,
--    },
--    [75225] = {
--        ["P1 Left"] = true,
--        ["P1 Circle"] = true,
--    },
--    [75316] = {
--        ["P1 L1"] = true,
--    },
--    [75468] = {
--        ["P1 Right"] = true,
--    },
--    [75470.49] = {
--        ["P1 Right"] = true,
--    },
--    [75525] = {
--        ["P1 Right"] = true,
--        ["P1 Down"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [75526] = {
--        ["P1 Up"] = true,
--    },
--    [75590] = {
--        ["P1 Square"] = true,
--    },
--    [75600] = {
--        ["P1 Triangle"] = true,
--    },
--    [75655.23] = {
--        ["P1 Right"] = true,
--    },
--    [75678] = {
--        ["P1 L2"] = true,
--    },
--    [75885.18] = {
--        ["P1 Right"] = true,
--    },
--    [75903] = {
--        ["P1 Square"] = true,
--    },
--    [75905] = {
--        ["P1 Square"] = true,
--    },
--    [75923] = {
--        ["P1 Triangle"] = true,
--    },
--    [75934] = {
--        ["P1 Left"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [76018] = {
--        ["P1 Left"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [76081] = {
--        ["P1 Left"] = true,
--        ["P1 Circle"] = true,
--    },
--    [76139] = {
--        ["P1 Circle"] = true,
--    },
--    [76200] = {
--        ["P1 Down"] = true,
--    },
--    [76201] = {
--        ["P1 Right"] = true,
--        ["P1 Down"] = true,
--    },
--    [76202] = {
--        ["P1 Right"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [76261] = {
--        ["P1 Down"] = true,
--    },
--    [76262] = {
--        ["P1 Right"] = true,
--        ["P1 Down"] = true,
--    },
--    [76263] = {
--        ["P1 Right"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [76338.12] = {
--        ["P1 Right"] = true,
--    },
--    [76350] = {
--        ["P1 Cross"] = true,
--        ["P1 Square"] = true,
--    },
--}