local Input = require('utils/input')
require('utils/macro')
require('macro/hayato-lessons')

-- Lesson 2.1
local input = Input()

macroHayatoLessons = MacroHayatoLessons(Macro(input))

return input:all()

--joypadSet6 = {
--    [12838] = {
--        ["P1 Cross"] = true,
--    },
--    [12840] = {
--        ["P1 Down"] = true,
--    },
--    [12842] = {
--        ["P1 Cross"] = true,
--    },
--    [12844] = {
--        ["P1 Cross"] = true,
--    },
--    [13623] = {
--        ["P1 Cross"] = true,
--    },
--    [13625] = {
--        ["P1 Cross"] = true,
--    },
--    [13777] = {
--        ["P1 Right"] = true,
--    },
--    [13779] = {
--        ["P1 Right"] = true,
--    },
--    [13849] = {
--        ["P1 Left"] = true,
--    },
--    [13851] = {
--        ["P1 Left"] = true,
--    },
--    [13921] = {
--        ["P1 Right"] = true,
--    },
--    [13923] = {
--        ["P1 Right"] = true,
--    },
--    [13993] = {
--        ["P1 Left"] = true,
--    },
--    [13995] = {
--        ["P1 Left"] = true,
--    },
--    [14065] = {
--        ["P1 Right"] = true,
--    },
--    [14067] = {
--        ["P1 Right"] = true,
--    },
--    [14137] = {
--        ["P1 Right"] = true,
--    },
--    [14139] = {
--        ["P1 Right"] = true,
--    },
--    [14209] = {
--        ["P1 Right"] = true,
--    },
--    [14211] = {
--        ["P1 Right"] = true,
--    },
--    [14281] = {
--        ["P1 Left"] = true,
--    },
--    [14283] = {
--        ["P1 Left"] = true,
--    },
--    [14353] = {
--        ["P1 Left"] = true,
--    },
--    [14355] = {
--        ["P1 Left"] = true,
--    },
--    [14425] = {
--        ["P1 Right"] = true,
--    },
--    [14427] = {
--        ["P1 Right"] = true,
--    },
--    [14799] = {
--        ["P1 Cross"] = true,
--    },
--    [14801] = {
--        ["P1 Cross"] = true,
--    },
--    [14806] = {
--        ["P1 Down"] = true,
--    },
--    [14808] = {
--        ["P1 Cross"] = true,
--    },
--}