require('utils/input')
require('utils/shortcut')

-- Lesson 2.4
local input = Input()
shortcut = Shortcut(input)

return input:all()

--joypadSet9 = {
--    [19390] = {
--        ["P1 Cross"] = true,
--    },
--    [19392] = {
--        ["P1 Down"] = true,
--    },
--    [19394] = {
--        ["P1 Cross"] = true,
--    },
--    [19396] = {
--        ["P1 Right"] = true,
--    },
--    [19398] = {
--        ["P1 Right"] = true,
--    },
--    [19400] = {
--        ["P1 Right"] = true,
--    },
--    [19402] = {
--        ["P1 Cross"] = true,
--    },
--    [20187] = {
--        ["P1 Cross"] = true,
--    },
--    [20189] = {
--        ["P1 Cross"] = true,
--    },
--    [20341] = {
--        ["P1 Right"] = true,
--    },
--    [20343] = {
--        ["P1 Right"] = true,
--    },
--    [20348] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [20464.17] = {
--        ["P1 Right"] = true,
--    },
--    [20532] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [20649.19] = {
--        ["P1 Right"] = true,
--    },
--    [20718] = {
--        ["P1 Down"] = true,
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [20818.19] = {
--        ["P1 Right"] = true,
--    },
--    [20865] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [20981.19] = {
--        ["P1 Left"] = true,
--    },
--    [21050] = {
--        ["P1 Down"] = true,
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [21150.19] = {
--        ["P1 Right"] = true,
--    },
--    [21198] = {
--        ["P1 Down"] = true,
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [21298.19] = {
--        ["P1 Right"] = true,
--    },
--    [21345] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [21461.19] = {
--        ["P1 Right"] = true,
--    },
--    [21529] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [21645.19] = {
--        ["P1 Right"] = true,
--    },
--    [21714] = {
--        ["P1 Down"] = true,
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [21814.19] = {
--        ["P1 Right"] = true,
--    },
--    [21861] = {
--        ["P1 Square"] = true,
--        ["P1 Triangle"] = true,
--    },
--    [22352] = {
--        ["P1 Cross"] = true,
--    },
--    [22354] = {
--        ["P1 Cross"] = true,
--    },
--    [22359] = {
--        ["P1 Down"] = true,
--    },
--    [22361] = {
--        ["P1 Cross"] = true,
--    },
--}